### PR TITLE
drop support for Node 16

### PR DESCRIPTION
**Pull request by fabnguess**

### CODE REVIEW

**Comment by PierreDemailly** [comment]
@fabnguess Can you fixes tests or do you need any guidance ? There type issue / missing deps (i don't know why)

**Comment by fabnguess** [comment]
Hi @PierreDemailly , I can't understand why the CI fails, can you guide me

**Comment by PierreDemailly** [comment]
@fabnguess I took the liberty to update your PR ;)

**Comment by fabnguess** [comment]
Hi @PierreDemailly , no problem and sorry for being less active. I'm finalizing a module for an app I'm working on, and I have to deliver it by the 31st. After that, I can focus more on organization.

**Review by fraxken — APPROVED** [review]

**Pull request merged**
